// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reserva.Infra.Data.Context;

#nullable disable

namespace Reserva.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reserva.Domain.Entidades.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QntQuartos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Hoteis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Cassino Hotel",
                            Nome = "Las Vegas Cassino & Hotel",
                            QntQuartos = 250
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Classic Hotel",
                            Nome = "England Palace",
                            QntQuartos = 50
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Beach Hotel",
                            Nome = "Miami Hotel",
                            QntQuartos = 120
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
